version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    container_name: db
    build: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: taxcalculator
      MYSQL_USER: taxcalculator
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
